# Generated by Django 5.2 on 2025-06-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('clave_hash', models.CharField(max_length=255)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
